I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/home.rpy", line 28, in script call
    call home_room
  File "game/script/home.rpy", line 42, in script
    return home_main
  File "game/script/home.rpy", line 42, in <module>
    return home_main
NameError: name 'home_main' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/home.rpy", line 28, in script call
    call home_room
  File "game/script/home.rpy", line 42, in script
    return home_main
  File "/Applications/renpy-7.4.4-sdk/renpy/ast.py", line 1507, in execute
    renpy.store._return = renpy.python.py_eval(self.expression)
  File "/Applications/renpy-7.4.4-sdk/renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-7.4.4-sdk/renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script/home.rpy", line 42, in <module>
    return home_main
NameError: name 'home_main' is not defined

Darwin-20.5.0-x86_64-i386-64bit
Ren'Py 7.4.4.1439
WonderWhy 1.0
Mon Jul 19 22:17:58 2021
